// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

package org.erlandhu.netty.protobuf.cmd;

public final class Cmd {
  private Cmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CmdDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;
    /**
     * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
     */
    CmdMessage getMessage();
    /**
     * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
     */
    CmdMessageOrBuilder getMessageOrBuilder();

    // optional bytes data = 2;
    /**
     * <code>optional bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    // optional sint32 appendCode = 3;
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    boolean hasAppendCode();
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    int getAppendCode();

    // optional bytes appendData = 4;
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    boolean hasAppendData();
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    com.google.protobuf.ByteString getAppendData();

    // optional bool compress = 5;
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    boolean hasCompress();
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    boolean getCompress();
  }
  /**
   * Protobuf type {@code org.erlandhu.netty.protobuf.cmd.CmdData}
   */
  public static final class CmdData extends
      com.google.protobuf.GeneratedMessage
      implements CmdDataOrBuilder {
    // Use CmdData.newBuilder() to construct.
    private CmdData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CmdData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CmdData defaultInstance;
    public static CmdData getDefaultInstance() {
      return defaultInstance;
    }

    public CmdData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CmdData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              CmdMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(CmdMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              appendCode_ = input.readSInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              appendData_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              compress_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CmdData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CmdData> PARSER =
        new com.google.protobuf.AbstractParser<CmdData>() {
      public CmdData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CmdData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CmdData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private CmdMessage message_;
    /**
     * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
     */
    public CmdMessage getMessage() {
      return message_;
    }
    /**
     * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
     */
    public CmdMessageOrBuilder getMessageOrBuilder() {
      return message_;
    }

    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    // optional sint32 appendCode = 3;
    public static final int APPENDCODE_FIELD_NUMBER = 3;
    private int appendCode_;
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    public boolean hasAppendCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 appendCode = 3;</code>
     */
    public int getAppendCode() {
      return appendCode_;
    }

    // optional bytes appendData = 4;
    public static final int APPENDDATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString appendData_;
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    public boolean hasAppendData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes appendData = 4;</code>
     */
    public com.google.protobuf.ByteString getAppendData() {
      return appendData_;
    }

    // optional bool compress = 5;
    public static final int COMPRESS_FIELD_NUMBER = 5;
    private boolean compress_;
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    public boolean hasCompress() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool compress = 5;</code>
     *
     * <pre>
     *data 是否压缩
     * </pre>
     */
    public boolean getCompress() {
      return compress_;
    }

    private void initFields() {
      message_ = CmdMessage.getDefaultInstance();
      data_ = com.google.protobuf.ByteString.EMPTY;
      appendCode_ = 0;
      appendData_ = com.google.protobuf.ByteString.EMPTY;
      compress_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, appendCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, appendData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, compress_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, appendCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, appendData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, compress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CmdData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CmdData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CmdData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CmdData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CmdData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CmdData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CmdData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CmdData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CmdData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CmdData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CmdData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.erlandhu.netty.protobuf.cmd.CmdData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CmdDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CmdData.class, Builder.class);
      }

      // Construct using org.erlandhu.netty.protobuf.cmd.Cmd.CmdData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (messageBuilder_ == null) {
          message_ = CmdMessage.getDefaultInstance();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        appendCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        appendData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        compress_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_descriptor;
      }

      public CmdData getDefaultInstanceForType() {
        return CmdData.getDefaultInstance();
      }

      public CmdData build() {
        CmdData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CmdData buildPartial() {
        CmdData result = new CmdData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.appendCode_ = appendCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.appendData_ = appendData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.compress_ = compress_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CmdData) {
          return mergeFrom((CmdData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CmdData other) {
        if (other == CmdData.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasAppendCode()) {
          setAppendCode(other.getAppendCode());
        }
        if (other.hasAppendData()) {
          setAppendData(other.getAppendData());
        }
        if (other.hasCompress()) {
          setCompress(other.getCompress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        if (!getMessage().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CmdData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CmdData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;
      private CmdMessage message_ = CmdMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          CmdMessage, CmdMessage.Builder, CmdMessageOrBuilder> messageBuilder_;
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public CmdMessage getMessage() {
        if (messageBuilder_ == null) {
          return message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public Builder setMessage(CmdMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public Builder setMessage(
          CmdMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public Builder mergeMessage(CmdMessage value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              message_ != CmdMessage.getDefaultInstance()) {
            message_ =
              CmdMessage.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = CmdMessage.getDefaultInstance();
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public CmdMessage.Builder getMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      public CmdMessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_;
        }
      }
      /**
       * <code>required .org.erlandhu.netty.protobuf.cmd.CmdMessage message = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          CmdMessage, CmdMessage.Builder, CmdMessageOrBuilder>
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              CmdMessage, CmdMessage.Builder, CmdMessageOrBuilder>(
                  message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // optional sint32 appendCode = 3;
      private int appendCode_ ;
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public boolean hasAppendCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public int getAppendCode() {
        return appendCode_;
      }
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public Builder setAppendCode(int value) {
        bitField0_ |= 0x00000004;
        appendCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 appendCode = 3;</code>
       */
      public Builder clearAppendCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        appendCode_ = 0;
        onChanged();
        return this;
      }

      // optional bytes appendData = 4;
      private com.google.protobuf.ByteString appendData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public boolean hasAppendData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public com.google.protobuf.ByteString getAppendData() {
        return appendData_;
      }
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public Builder setAppendData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appendData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes appendData = 4;</code>
       */
      public Builder clearAppendData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appendData_ = getDefaultInstance().getAppendData();
        onChanged();
        return this;
      }

      // optional bool compress = 5;
      private boolean compress_ ;
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public boolean hasCompress() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public boolean getCompress() {
        return compress_;
      }
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public Builder setCompress(boolean value) {
        bitField0_ |= 0x00000010;
        compress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool compress = 5;</code>
       *
       * <pre>
       *data 是否压缩
       * </pre>
       */
      public Builder clearCompress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        compress_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.erlandhu.netty.protobuf.cmd.CmdData)
    }

    static {
      defaultInstance = new CmdData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.erlandhu.netty.protobuf.cmd.CmdData)
  }

  public interface CmdMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required sint32 messageId = 1;
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    int getMessageId();

    // required sint32 serverId = 2;
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    boolean hasServerId();
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    int getServerId();

    // optional sint32 playerId = 3;
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    int getPlayerId();

    // optional int64 clientTime = 4;
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    boolean hasClientTime();
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    long getClientTime();

    // optional int64 serverTime = 5;
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    boolean hasServerTime();
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    long getServerTime();

    // optional sint32 index = 6;
    /**
     * <code>optional sint32 index = 6;</code>
     *
     * <pre>
     *命令序号(用于标识唯一请求)
     * </pre>
     */
    boolean hasIndex();
    /**
     * <code>optional sint32 index = 6;</code>
     *
     * <pre>
     *命令序号(用于标识唯一请求)
     * </pre>
     */
    int getIndex();

    // optional sint32 serverIndex = 7;
    /**
     * <code>optional sint32 serverIndex = 7;</code>
     */
    boolean hasServerIndex();
    /**
     * <code>optional sint32 serverIndex = 7;</code>
     */
    int getServerIndex();

    // optional sint32 seq = 8;
    /**
     * <code>optional sint32 seq = 8;</code>
     */
    boolean hasSeq();
    /**
     * <code>optional sint32 seq = 8;</code>
     */
    int getSeq();

    // optional sint32 ack = 9;
    /**
     * <code>optional sint32 ack = 9;</code>
     */
    boolean hasAck();
    /**
     * <code>optional sint32 ack = 9;</code>
     */
    int getAck();
  }
  /**
   * Protobuf type {@code org.erlandhu.netty.protobuf.cmd.CmdMessage}
   */
  public static final class CmdMessage extends
      com.google.protobuf.GeneratedMessage
      implements CmdMessageOrBuilder {
    // Use CmdMessage.newBuilder() to construct.
    private CmdMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CmdMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CmdMessage defaultInstance;
    public static CmdMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CmdMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CmdMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageId_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverId_ = input.readSInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              playerId_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              clientTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              serverTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              index_ = input.readSInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              serverIndex_ = input.readSInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              seq_ = input.readSInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              ack_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CmdMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CmdMessage> PARSER =
        new com.google.protobuf.AbstractParser<CmdMessage>() {
      public CmdMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CmdMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CmdMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required sint32 messageId = 1;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint32 messageId = 1;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    // required sint32 serverId = 2;
    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverId_;
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required sint32 serverId = 2;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    // optional sint32 playerId = 3;
    public static final int PLAYERID_FIELD_NUMBER = 3;
    private int playerId_;
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 playerId = 3;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // optional int64 clientTime = 4;
    public static final int CLIENTTIME_FIELD_NUMBER = 4;
    private long clientTime_;
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    public boolean hasClientTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 clientTime = 4;</code>
     */
    public long getClientTime() {
      return clientTime_;
    }

    // optional int64 serverTime = 5;
    public static final int SERVERTIME_FIELD_NUMBER = 5;
    private long serverTime_;
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    public boolean hasServerTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 serverTime = 5;</code>
     */
    public long getServerTime() {
      return serverTime_;
    }

    // optional sint32 index = 6;
    public static final int INDEX_FIELD_NUMBER = 6;
    private int index_;
    /**
     * <code>optional sint32 index = 6;</code>
     *
     * <pre>
     *命令序号(用于标识唯一请求)
     * </pre>
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional sint32 index = 6;</code>
     *
     * <pre>
     *命令序号(用于标识唯一请求)
     * </pre>
     */
    public int getIndex() {
      return index_;
    }

    // optional sint32 serverIndex = 7;
    public static final int SERVERINDEX_FIELD_NUMBER = 7;
    private int serverIndex_;
    /**
     * <code>optional sint32 serverIndex = 7;</code>
     */
    public boolean hasServerIndex() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional sint32 serverIndex = 7;</code>
     */
    public int getServerIndex() {
      return serverIndex_;
    }

    // optional sint32 seq = 8;
    public static final int SEQ_FIELD_NUMBER = 8;
    private int seq_;
    /**
     * <code>optional sint32 seq = 8;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional sint32 seq = 8;</code>
     */
    public int getSeq() {
      return seq_;
    }

    // optional sint32 ack = 9;
    public static final int ACK_FIELD_NUMBER = 9;
    private int ack_;
    /**
     * <code>optional sint32 ack = 9;</code>
     */
    public boolean hasAck() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional sint32 ack = 9;</code>
     */
    public int getAck() {
      return ack_;
    }

    private void initFields() {
      messageId_ = 0;
      serverId_ = 0;
      playerId_ = 0;
      clientTime_ = 0L;
      serverTime_ = 0L;
      index_ = 0;
      serverIndex_ = 0;
      seq_ = 0;
      ack_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, serverId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, playerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, clientTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, serverTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeSInt32(6, index_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeSInt32(7, serverIndex_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeSInt32(8, seq_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeSInt32(9, ack_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, serverId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, playerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, clientTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, serverTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, index_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, serverIndex_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(8, seq_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(9, ack_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CmdMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CmdMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CmdMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CmdMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CmdMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CmdMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CmdMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CmdMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CmdMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CmdMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CmdMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.erlandhu.netty.protobuf.cmd.CmdMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CmdMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CmdMessage.class, Builder.class);
      }

      // Construct using org.erlandhu.netty.protobuf.cmd.Cmd.CmdMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        clientTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        serverTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        serverIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        ack_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_descriptor;
      }

      public CmdMessage getDefaultInstanceForType() {
        return CmdMessage.getDefaultInstance();
      }

      public CmdMessage build() {
        CmdMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CmdMessage buildPartial() {
        CmdMessage result = new CmdMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientTime_ = clientTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serverTime_ = serverTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.index_ = index_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.serverIndex_ = serverIndex_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.seq_ = seq_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.ack_ = ack_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CmdMessage) {
          return mergeFrom((CmdMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CmdMessage other) {
        if (other == CmdMessage.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasClientTime()) {
          setClientTime(other.getClientTime());
        }
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasServerIndex()) {
          setServerIndex(other.getServerIndex());
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasAck()) {
          setAck(other.getAck());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        if (!hasServerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CmdMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CmdMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required sint32 messageId = 1;
      private int messageId_ ;
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0;
        onChanged();
        return this;
      }

      // required sint32 serverId = 2;
      private int serverId_ ;
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000002;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 serverId = 2;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // optional sint32 playerId = 3;
      private int playerId_ ;
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000004;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 playerId = 3;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // optional int64 clientTime = 4;
      private long clientTime_ ;
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public boolean hasClientTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public Builder setClientTime(long value) {
        bitField0_ |= 0x00000008;
        clientTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clientTime = 4;</code>
       */
      public Builder clearClientTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 serverTime = 5;
      private long serverTime_ ;
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public boolean hasServerTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public Builder setServerTime(long value) {
        bitField0_ |= 0x00000010;
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 serverTime = 5;</code>
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverTime_ = 0L;
        onChanged();
        return this;
      }

      // optional sint32 index = 6;
      private int index_ ;
      /**
       * <code>optional sint32 index = 6;</code>
       *
       * <pre>
       *命令序号(用于标识唯一请求)
       * </pre>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional sint32 index = 6;</code>
       *
       * <pre>
       *命令序号(用于标识唯一请求)
       * </pre>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>optional sint32 index = 6;</code>
       *
       * <pre>
       *命令序号(用于标识唯一请求)
       * </pre>
       */
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000020;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 index = 6;</code>
       *
       * <pre>
       *命令序号(用于标识唯一请求)
       * </pre>
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000020);
        index_ = 0;
        onChanged();
        return this;
      }

      // optional sint32 serverIndex = 7;
      private int serverIndex_ ;
      /**
       * <code>optional sint32 serverIndex = 7;</code>
       */
      public boolean hasServerIndex() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional sint32 serverIndex = 7;</code>
       */
      public int getServerIndex() {
        return serverIndex_;
      }
      /**
       * <code>optional sint32 serverIndex = 7;</code>
       */
      public Builder setServerIndex(int value) {
        bitField0_ |= 0x00000040;
        serverIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 serverIndex = 7;</code>
       */
      public Builder clearServerIndex() {
        bitField0_ = (bitField0_ & ~0x00000040);
        serverIndex_ = 0;
        onChanged();
        return this;
      }

      // optional sint32 seq = 8;
      private int seq_ ;
      /**
       * <code>optional sint32 seq = 8;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional sint32 seq = 8;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>optional sint32 seq = 8;</code>
       */
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000080;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 seq = 8;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000080);
        seq_ = 0;
        onChanged();
        return this;
      }

      // optional sint32 ack = 9;
      private int ack_ ;
      /**
       * <code>optional sint32 ack = 9;</code>
       */
      public boolean hasAck() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional sint32 ack = 9;</code>
       */
      public int getAck() {
        return ack_;
      }
      /**
       * <code>optional sint32 ack = 9;</code>
       */
      public Builder setAck(int value) {
        bitField0_ |= 0x00000100;
        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 ack = 9;</code>
       */
      public Builder clearAck() {
        bitField0_ = (bitField0_ & ~0x00000100);
        ack_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.erlandhu.netty.protobuf.cmd.CmdMessage)
    }

    static {
      defaultInstance = new CmdMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.erlandhu.netty.protobuf.cmd.CmdMessage)
  }

  public interface CmdTestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 id = 1;
    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code org.erlandhu.netty.protobuf.cmd.CmdTest}
   */
  public static final class CmdTest extends
      com.google.protobuf.GeneratedMessage
      implements CmdTestOrBuilder {
    // Use CmdTest.newBuilder() to construct.
    private CmdTest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CmdTest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CmdTest defaultInstance;
    public static CmdTest getDefaultInstance() {
      return defaultInstance;
    }

    public CmdTest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CmdTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CmdTest.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CmdTest> PARSER =
        new com.google.protobuf.AbstractParser<CmdTest>() {
      public CmdTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CmdTest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CmdTest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CmdTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CmdTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CmdTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CmdTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CmdTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CmdTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CmdTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CmdTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CmdTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CmdTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CmdTest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.erlandhu.netty.protobuf.cmd.CmdTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CmdTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CmdTest.class, Builder.class);
      }

      // Construct using org.erlandhu.netty.protobuf.cmd.Cmd.CmdTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmd.internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_descriptor;
      }

      public CmdTest getDefaultInstanceForType() {
        return CmdTest.getDefaultInstance();
      }

      public CmdTest build() {
        CmdTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CmdTest buildPartial() {
        CmdTest result = new CmdTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CmdTest) {
          return mergeFrom((CmdTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CmdTest other) {
        if (other == CmdTest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CmdTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CmdTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 id = 1;
      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.erlandhu.netty.protobuf.cmd.CmdTest)
    }

    static {
      defaultInstance = new CmdTest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.erlandhu.netty.protobuf.cmd.CmdTest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tCmd.proto\022\037org.erlandhu.netty.protobuf" +
      ".cmd\"\217\001\n\007CmdData\022<\n\007message\030\001 \002(\0132+.org." +
      "erlandhu.netty.protobuf.cmd.CmdMessage\022\014" +
      "\n\004data\030\002 \001(\014\022\022\n\nappendCode\030\003 \001(\021\022\022\n\nappe" +
      "ndData\030\004 \001(\014\022\020\n\010compress\030\005 \001(\010\"\251\001\n\nCmdMe" +
      "ssage\022\021\n\tmessageId\030\001 \002(\021\022\020\n\010serverId\030\002 \002" +
      "(\021\022\020\n\010playerId\030\003 \001(\021\022\022\n\nclientTime\030\004 \001(\003" +
      "\022\022\n\nserverTime\030\005 \001(\003\022\r\n\005index\030\006 \001(\021\022\023\n\013s" +
      "erverIndex\030\007 \001(\021\022\013\n\003seq\030\010 \001(\021\022\013\n\003ack\030\t \001" +
      "(\021\"#\n\007CmdTest\022\n\n\002id\030\001 \002(\r\022\014\n\004name\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_erlandhu_netty_protobuf_cmd_CmdData_descriptor,
              new String[] { "Message", "Data", "AppendCode", "AppendData", "Compress", });
          internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_erlandhu_netty_protobuf_cmd_CmdMessage_descriptor,
              new String[] { "MessageId", "ServerId", "PlayerId", "ClientTime", "ServerTime", "Index", "ServerIndex", "Seq", "Ack", });
          internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_erlandhu_netty_protobuf_cmd_CmdTest_descriptor,
              new String[] { "Id", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
